datasource.type=JSON
json.apiReadAccessToken=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5ZWI4OWFhZmUyNWExYWYxNDc1MzYxNGNhMDgzNDJlYyIsIm5iZiI6MTU5NTcxNjI0NS4xNTUsInN1YiI6IjVmMWNiMjk1MGJiMDc2MDAzNGYxMDUzOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.auv8FpgH55cn4CWUnkVcldTqGtlzond1hVer9VJlEcQ
json.apiURL=https://api.themoviedb.org/3/search/movie?
xml.apiurl=https://www.omdbapi.com/?type=movie&apikey=359a6530&r=xml
mysql.connectionString=jdbc:mysql://35.209.160.138:3306/dbuiuv3ukrxrpd?user=uygxgocansyoc&password=nov5x97opwxv&sslmode=disabled